# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: Configuration
  items:
    - label: "Theme"
      link: "/config/theme"
- label: Components
  items:
    - label: "H1"
      link: "/components/h1"
    - label: "H2"
      link: "/components/h2"
    - label: "H3"
      link: "/components/h3"
    - label: "Button"
      link: "/components/button"
    - label: "Badge"
      link: "/components/badge"
- label: Usage
  items:
    - label: "Creating docs"
      link: "/usage/creating-docs"
    - label: "Navigation"
      link: "/usage/navigation"
    - label: "Shadowing"
      link: "/usage/shadowing"
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: "Github"
      link: https://github.com/AthenicAustria/athenic-ui
