# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: Configuration
  items:
    - label: "Theme"
      link: "/config/theme"
- label: Components
  items:
    - label: "H1"
      link: "/components/h1"
    - label: "H2"
      link: "/components/h2"
    - label: "H3"
      link: "/components/h3"
    - label: "Button"
      link: "/components/button"
    - label: "Badge"
      link: "/components/badge"
    - label: "Card"
      link: "/components/card"
    - label: "Alert"
      link: "components/alert"
    - label: "Avatar"
      link: "components/avatar"
    - label: "BurgerMenu"
      link: "components/burgermenu"
    - label: "Collapse"
      link: "components/collapse"
    - label: "Comment"
      link: "components/comment"
    - label: "Counter"
      link: "components/counter"
    - label: "Drawer"
      link: "components/drawer"
    - label: "Link"
      link: "components/link"
    - label: "Menu"
      link: "components/menu"
    - label: "Menu-Item"
      link: "components/menuItem"
    - label: "Modal"
      link: "components/modal"
    - label: "NavBar"
      link: "components/navbar"
    - label: "OTP-Input"
      link: "components/otpinput"
    - label: "Pop-Over"
      link: "components/popover"
    - label: "Radio-Group"
      link: "components/radiogroup"
    - label: "Rating"
      link: "components/rating"
    - label: "Search-Input"
      link: "components/searchinput"
- label: Usage
  items:
    - label: "Creating docs"
      link: "/usage/creating-docs"
    - label: "Navigation"
      link: "/usage/navigation"
    - label: "Shadowing"
      link: "/usage/shadowing"
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: "Github"
      link: https://github.com/AthenicAustria/athenic-ui
